// <auto-generated />
using System;
using GlobalTicket.TicketManagment.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalTicket.TicketManagment.Persistence.Migrations
{
    [DbContext(typeof(GloboTicketDbContext))]
    partial class GloboTicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GloboTicket.TicketManagment.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreateDate = new DateTime(2025, 12, 22, 13, 57, 42, 145, DateTimeKind.Local).AddTicks(3224),
                            CreatedBy = "System",
                            Name = "Concerts"
                        },
                        new
                        {
                            CategoryId = new Guid("fe9a5e7d-5d6c-4f3b-8d9e-8e1c2d5c8bce"),
                            CreateDate = new DateTime(2025, 12, 22, 13, 57, 42, 145, DateTimeKind.Local).AddTicks(3429),
                            CreatedBy = "System",
                            Name = "Musicals"
                        },
                        new
                        {
                            CategoryId = new Guid("7d4e4b6c-2a1f-4f3e-9f8e-3c2b1a0d9e8f"),
                            CreateDate = new DateTime(2025, 12, 22, 13, 57, 42, 145, DateTimeKind.Local).AddTicks(3478),
                            CreatedBy = "System",
                            Name = "Plays"
                        },
                        new
                        {
                            CategoryId = new Guid("a1b2c3d4-e5f6-4789-abcd-1234567890ab"),
                            CreateDate = new DateTime(2025, 12, 22, 13, 57, 42, 145, DateTimeKind.Local).AddTicks(3523),
                            CreatedBy = "System",
                            Name = "Conferences"
                        });
                });

            modelBuilder.Entity("GloboTicket.TicketManagment.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-ef8a7875835c"),
                            Artist = "John Egbert",
                            CategoryId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreateDate = new DateTime(2025, 12, 22, 13, 57, 42, 145, DateTimeKind.Local).AddTicks(3601),
                            CreatedBy = "System",
                            Date = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join John for his farwell tour across 15 continents. John really needs no introduction since he has already sold over 25 million albums worldwide.",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/GloboTicket/concert1.png",
                            Name = "John Egbert Live",
                            Price = "65"
                        },
                        new
                        {
                            Id = new Guid("d7b4f2e2-5d3c-4a8c-9a6f-8d9e7c6b5a4f"),
                            Artist = "Michael Johnson",
                            CategoryId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            CreateDate = new DateTime(2025, 12, 22, 13, 57, 42, 145, DateTimeKind.Local).AddTicks(3663),
                            CreatedBy = "System",
                            Date = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Michael Johnson doesn't need an introduction either. His 25th album is coming out this fall and we are going to celebrate the launch with a big concert.",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/GloboTicket/concert2.png",
                            Name = "The State of Affairs: Michael Live!",
                            Price = "85"
                        },
                        new
                        {
                            Id = new Guid("a1c2e3f4-5678-4b9a-bcde-1234567890ab"),
                            Artist = "Nick Sailor",
                            CategoryId = new Guid("fe9a5e7d-5d6c-4f3b-8d9e-8e1c2d5c8bce"),
                            CreateDate = new DateTime(2025, 12, 22, 13, 57, 42, 145, DateTimeKind.Local).AddTicks(3710),
                            CreatedBy = "System",
                            Date = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The critics are raving about this new musical production that takes you on an emotional ride through the universe.",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/GloboTicket/musical1.png",
                            Name = "To the Moon and Back",
                            Price = "135"
                        });
                });

            modelBuilder.Entity("GloboTicket.TicketManagment.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OrderPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderToral")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GloboTicket.TicketManagment.Domain.Entities.Event", b =>
                {
                    b.HasOne("GloboTicket.TicketManagment.Domain.Entities.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GloboTicket.TicketManagment.Domain.Entities.Category", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
